# Each YAML document has the following schema:
#
# from: "the path to the redirected URL"
# to: "the path to the new location for the resource"
# type: "currently this script only supports 'redirect', and
#        ignores all documents with another type."
# code: "the HTTP redirect code. Raises exception if not 301, 302, 303."
# outputs: "a list of branches/paths as follows:"
#
# - 'all': generates redirects for all published branches, but *not* 'manual'. But giza will take care of manual as part of integration.yaml logic in redirects.py
#
# - '<branch>': generates redirects for a specific branch.
#
# - 'before-<branch>': generates redirects for all branches that
#   reflect releases previous to the specified branch. (Inclusive.)
#
# - 'after-<branch>': generates redirects for all branches that
#   reflect releases after the specified branch. (Non-inclusive.)
#
# All paths are relative to the ``source/`` directory.
#
########################################################################
### Giza requires this file, even if no redirects
### More as a safety -- in case, we remove redirects during deploys
from: '/'
to: '/master'
type: 'redirect'
code: 301
outputs:
  - {'/mongoid': 'https://docs.mongodb.com/mongoid'}
...
