#!/usr/bin/env ruby

$: << File.join(File.dirname(__FILE__), '../lib')

require 'optparse'
require 'child_process_helper'
autoload :FileUtils, 'fileutils'

options = {}

OptionParser.new do |opts|
  opts.on('-p', '--path=PATH', 'Build docs at PATH') do |v|
    options[:path] = v
  end
end.parse!

project = ARGV.shift

unless %w(ruby mongoid).include?(project)
  raise "Usage: build-docker [-p path] ruby|mongoid"
end

FileUtils.rm_rf('.src')
if options[:path]
  ChildProcessHelper.check_call([
    'rsync',
      '--exclude', '.git', '--exclude', 'pkg', '--exclude', '*.gem',
      '--exclude', 'yard-docs',
      '--delete', '-a', options[:path] + '/', '.src',
  ])
end

ChildProcessHelper.check_call(%w(docker build -t docs-unified .))

ChildProcessHelper.check_call(%W(
docker run -itv #{Dir.pwd}/build:/build docs-unified
  sh -c) + ["./script/run #{project} build && rsync -a --delete #{project}/build/ /build"])
