#!/usr/bin/env ruby

$: << File.join(File.dirname(__FILE__), '../lib')

unless ARGV.length == 2
  raise "Usage: script/run <ruby|mongoid> <tut|build|deploy>"
end

project, action = ARGV

unless %w(ruby mongoid).include?(project)
  raise "Invalid project: #{project}. Use ruby or mongoid"
end

unless %w(tut build deploy).include?(action)
  raise "Invalid action: #{action}. Use tut, build or deploy"
end

require 'runner'

Runner.new(project).send(action)
