# Each YAML document has the following schema:
#
# from: "the path to the redirected URL"
# to: "the path to the new location for the resource"
# type: "currently this script only supports 'redirect', and
#        ignores all documents with another type."
# code: "the HTTP redirect code. Raises exception if not 301, 302, 303."
# outputs: "a list of branches/paths as follows:"
#
# - 'all': generates redirects for all published branches, but *not* 'manual'. But giza will take care of manual as part of integration.yaml logic in redirects.py
#
# - '<branch>': generates redirects for a specific branch.
#
# - 'before-<branch>': generates redirects for all branches that
#   reflect releases previous to the specified branch. (Inclusive.)
#
# - 'after-<branch>': generates redirects for all branches that
#   reflect releases after the specified branch. (Non-inclusive.)
#
# All paths are relative to the ``source/`` directory.
#
########################################################################
### Giza requires this file, even if no redirects
### More as a safety -- in case, we remove redirects during deploys
from: /mongoid-tutorials
to: /
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
---
type: 'redirect'
code: 301
from: /mongoid
to: /
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}

type: 'redirect'
code: 301
---
from: /tutorials/mongoid-callbacks
to: /tutorials/mongoid-callbacks
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
type: 'redirect'
code: 301
---
from: /tutorials/mongoid-installation
to: /tutorials/mongoid-installation
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/mongoid-queries
to: /tutorials/mongoid-queries
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/mongoid-upgrade
to: /tutorials/mongoid-upgrade
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/mongoid-documents
to: /tutorials/mongoid-documents
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/mongoid-nested-attributes
to: /tutorials/mongoid-nested-attributes
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/mongoid-rails
to: /tutorials/mongoid-rails
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/mongoid-validation
to: /tutorials/mongoid-validation
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/mongoid-indexes
to: /tutorials/mongoid-indexes
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/mongoid-persistence
to: /tutorials/mongoid-persistence
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/mongoid-relations
to: /tutorials/mongoid-relations
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /mongoid-tutorials-6.0
to: /
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/6.1.0/mongoid-callbacks
to: /tutorials/mongoid-callbacks
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/6.1.0/mongoid-installation
to: /tutorials/mongoid-installation
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/6.1.0/mongoid-queries
to: /tutorials/mongoid-queries
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/6.1.0/mongoid-upgrade
to: /tutorials/mongoid-upgrade
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/6.1.0/mongoid-documents
to: /tutorials/mongoid-documents
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/6.1.0/mongoid-nested-attributes
to: /tutorials/mongoid-nested-attributes
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/6.1.0/mongoid-rails
to: /tutorials/mongoid-rails
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/6.1.0/mongoid-validation
to: /tutorials/mongoid-validation
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/6.1.0/mongoid-indexes
to:  /tutorials/mongoid-indexes
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/6.1.0/mongoid-persistence
to:  /tutorials/mongoid-persistence
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /tutorials/6.1.0/mongoid-relations
to: /tutorials/mongoid-relations
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/master'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/master'}
---
from: /mongoid-tutorials-5.2
to: /
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/v5.2'}
---
from: /mongoid-tutorials-5.1
to: /
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/v5.2'}
---
from: /tutorials/5.2.0/mongoid-callbacks
to: /tutorials/mongoid-callbacks
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/v5.2'}
---
from: /tutorials/5.2.0/mongoid-installation
to: /tutorials/mongoid-installation
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/v5.2'}
---
from: /tutorials/5.2.0/mongoid-queries
to: /tutorials/mongoid-queries
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/v5.2'}
---
from: /tutorials/5.2.0/mongoid-upgrade
to: /tutorials/mongoid-upgrade
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/v5.2'}
---
from: /tutorials/5.2.0/mongoid-documents
to: /tutorials/mongoid-documents
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/v5.2'}
---
from: /tutorials/5.2.0/mongoid-nested-attributes
to: /tutorials/mongoid-nested-attributes
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/v5.2'}
---
from: /tutorials/5.2.0/mongoid-rails
to: /tutorials/mongoid-rails
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/v5.2'}
---
from: /tutorials/5.2.0/mongoid-validation
to: /tutorials/mongoid-validation
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/v5.2'}
---
from: /tutorials/5.2.0/mongoid-indexes
to: /tutorials/mongoid-indexes
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/v5.2'}
---
from: /tutorials/5.2.0/mongoid-persistence
to: /tutorials/mongoid-persistence
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/v5.2'}
---
from: /tutorials/5.2.0/mongoid-relations
to: /tutorials/mongoid-relations
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver/master': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.4': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.3': 'https://docs.mongodb.com/mongoid/v5.2'}
  - {'/ruby-driver/v2.2': 'https://docs.mongodb.com/mongoid/v5.2'}
...
