project: 'ruby-manual'
master_doc: 'index'
logo: ".static/logo.png"
paths:
  static: ['source/.static']
theme:
  name: 'ruby-driver'
  project: 'docs-ruby'
  google_analytics: 'UA-7301842-8'
  book_path_base: 'ruby-driver'
  repo: 'docs-ruby'
  jira: 'DOCS'
  sitename: 'Ruby Driver'
  nav_excluded:
     - /bson-tutorials
     - /mongoid-tutorials
sidebars:
  '**':
    - 'pagenav.html'
...